### ISSUE TITLE
When the environment variable name is missing in db-tunnel command 'no help message' is displayed

### ISSUE THREAD

**Issue by Soulou** [Scalingo/cli#294]

**Comment by Soulou** [comment]
It should display the help for the command db-tunnel which exists I think

**Comment by MrMourse** [comment]
I don't understand exactly what it should be done.
When i use `scalingo -a myapp db-tunnel ` without the last argument, the help is displayed by default

The behavior of `scalingo db-tunnel` without the both arguments, should return also the help?
And what about `scalingo db-tunnel my_url` ?

**Comment by bragagia** [comment]
I think the PR #290 solved this bug. Does the release build (where this PR is not currently used) have the same behavior ?

**Comment by MrMourse** [comment]
Ok the bug seems to be only on the production environnment.

Prod:
![prod](https://user-images.githubusercontent.com/25328446/27276684-37126640-54dc-11e7-89f6-ac9ffd3c1bf1.png)

Develop:
![developpment](https://user-images.githubusercontent.com/25328446/27276715-51eacd4a-54dc-11e7-8625-cfc1d1d41c90.png)

**Comment by Soulou** [comment]
Ok interesting, can you confirm it returns exactly what is returned by

```
scalingo help db-tunnel
```

?

**Comment by MrMourse** [comment]
Yes, it's exactly the same.
