### ISSUE TITLE
Support new format for SSH private keys

### ISSUE THREAD

**Issue by Soulou** [Scalingo/cli#389]
ssh-keygen on some system seems to generate `OPENSSH PRIVATE KEY` instead of `RSA PRIVATE KEY` in the private key, we need to add the compatibility.

Some references:

https://github.com/hierynomus/sshj/issues/276
https://github.com/duplicati/duplicati/issues/3360

**Comment by dkocher** [comment]
This is as of OpenSSH 7.8 the default.

> * ssh-keygen(1): write OpenSSH format private keys by default
   instead of using OpenSSL's PEM format. The OpenSSH format,
   supported in OpenSSH releases since 2014 and described in the
   PROTOCOL.key file in the source distribution, offers substantially
   better protection against offline password guessing and supports
   key comments in private keys. If necessary, it is possible to write
   old PEM-style keys by adding "-m PEM" to ssh-keygen's arguments
   when generating or updating a key.

Workaround is to use `ssh-keygen -m PEM`.

**Comment by dkocher** [comment]
The failure is a message like `Bad item length: -1512035316` which is caused from reading the key in [OpenSSHKeyV1KeyFile](https://github.com/hierynomus/sshj/blob/master/src/main/java/com/hierynomus/sshj/userauth/keyprovider/OpenSSHKeyV1KeyFile.java#L193).

**Comment by EtienneM** [comment]
Stack trace is:
```
[/home/leo/Projects/Go/src/github.com/Scalingo/cli/db/tunnel.go:61](https://github.com/Scalingo/cli/blob/master/db/tunnel.go#L61): fail to connect to SSH server
[/home/leo/Projects/Go/src/github.com/Scalingo/cli/net/ssh/client.go:37](https://github.com/Scalingo/cli/blob/master/net/ssh/client.go#L37): 
[/home/leo/Projects/Go/src/github.com/Scalingo/cli/crypto/sshkeys/read.go:55](https://github.com/Scalingo/cli/blob/master/crypto/sshkeys/read.go#L55): Invalid SSH key or password: ssh: unhandled key type
```
