### ISSUE TITLE
[Detached one-off] Impossible to use an uploaded file in a detached one-off

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/cli#508]
Without the `--detached` flag:

```
calingo -a rss-bridge run -f ./test-one-off cat /tmp/uploads/test-one-off                              1 ↵
Upload /home/EtienneM/Documents/Scalingo/test-one-off to container.
-----> Connecting to container [one-off-5728]...  
-----> Process 'cat /tmp/uploads/test-one-off' is starting...  

toto
fezfezfez
fefzefze

```

With the detached flag:

```
╰─$ oscalingo -a rss-bridge run -f ./test-one-off --detached cat /tmp/uploads/test-one-off                 130 ↵
Starting one-off 'cat /tmp/uploads/test-one-off' for app 'rss-bridge'.
Run `scalingo -a rss-bridge logs -F one-off-4984` to get the output
╭─emichon@biniou ~/Documents/Scalingo 2.6.5
╰─$ oscalingo -a rss-bridge logs -F one-off-4984                                          
2019-10-24 12:20:50.618749016 +0200 CEST [manager] container [one-off-4984] (5db17b0101dcea1bc62871cc) started with the command 'cat /tmp/uploads/test-one-off'
2019-10-24 12:20:52.355839106 +0200 CEST [manager] container [one-off-4984] (5db17b0101dcea1bc62871cc) has stopped with exit code: 1

```

https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/all/conversations/24240504403

**Comment by EtienneM** [comment]
Up up

**Comment by johnsudaar** [comment]
Up ;) 
https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/conversation/12375700040287

**Comment by johnsudaar** [comment]
It's not a good first issue though. This will need some work in our API and internal services in order to be implemented correctly.

**Comment by johnsudaar** [comment]
Because currently the process to start an attached one-off is the following:
1. The CLI calls the API (on the /run endpoint)
2. The API calls our scheduler
3. The scheduler calls our node
4. The container is created on the node
5. (if there is a file to upload) The CLI then calls the one-off service (through the attach URL)  to upload the file (/upload route)
6. The CLI calls the one-off service (still through the attach URL) and attach the container
7. The attach call then start the container

However when it's detached the workflow is the following:

1. The CLI calls the API (on the /run endpoint)
2. The API calls our scheduler
3. The scheduler calls our node
4. The container is created AND STARTED on the node

So even if we add a step 5:
5. (if there is a file to upload) The CLI then calls the one-off service (through the attach URL)  to upload the file (/upload route)

It wouldn't be a valid solution since there will be a race condition between the container starting and the file being uploaded.

**Comment by Soulou** [comment]
From what was said, we don't want to handle it for now, the CLI should clearly refuse to upload a file when starting a detached one-off
