### ISSUE TITLE
fail to connect to SSH server: open /Users/USER/.ssh/id_rsa: no such file or directory

### ISSUE THREAD

**Issue by jnylen** [Scalingo/cli#779]
Hi,

At our company the standard ssh key we require the developers to use is not RSA but ed25519, is this something the db-tunnel will support in the future?

**Comment by jnylen** [comment]
Passing in `-i <path>/id_ed25519` works but maybe this can be done per auto?

**Comment by EtienneM** [comment]
Hi,

Our DB tunnel supports ed25519 keys out of the box. Can you contact us on the support chat embedded on your web dashboard so that we figure out why it does not work on your side?

**Comment by filippo-orru** [comment]
I also had trouble with this. Not sure why, I would expect that the cli automatically uses the key I added using `scalingo keys-add "Laptop SSH key" $HOME/.ssh/id_ed25519.pub`, instead of trying to read a key from an "arbitrary" location.
In our limited testing, it also seemed to ignore the path set in the `.ssh/config` file.
