### ISSUE TITLE
"scalingo deploy"

### ISSUE THREAD

**Issue by yannski** [Scalingo/cli#84]
Would be handy :)

**Comment by Soulou** [comment]
Do we really need this, because it would completely hide that we are using a standard tool which is GIT, I think that's something important.

One argument for this feature is:
* Windows users : some of them don't have GIT installed, however it's pretty easy to install, the official installer is well done. It would be useful to build something with a `git` client implementation in Go, like this, everything would be in the binary, no `git` installation required. But in this case, I won't release that for the 1.0.0.

**Comment by EtienneM** [comment]
We now have `scalingo deploy` for archive
